[server]
port = 8080
ip = "127.0.0.1"
host = "http://localhost"

[tracing]
enable = true
env_filter = "shipwright=debug,tower_http=debug,axum::rejection=trace"

[database]
url = "sqlite://db/shipwright.db"

[static_assets]
precompressed = false
path = "assets/static"

[mailer]
base_url = "https://api.resend.com"
sender = "dev@notebar.io"
timeout = 2000

[worker]
database_url = "sqlite://db/shipwright_jobs.db"
