[server]
port = 8080
ip = "0.0.0.0"
host = "http://localhost"

[tracing]
enable = true
env_filter = "shipwright=debug,tower_http=debug,axum::rejection=trace"

[database]
url = "sqlite://../db/shipwright__test.db"

[static_assets]
precompressed = false
path = "assets/static"

[mailer]
base_url = "SET_BY_WIREMOCK_IN_TEST_ENVIRONMENT"
sender = "dev@notebar.io"
timeout = 2000

[worker]
database_url = "sqlite://../db/shipwright_jobs__test.db"
